name: intume
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.8.3
  table_calendar: ^3.0.9
  intl: ^0.20.2
  provider: ^6.0.5
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  uuid: ^4.3.3
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
